name: Docker PostGIS CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:
  make-docker-images:
    strategy:
      matrix:
        postgres: [9.5, 9.6, 10, 11, 12, 13]
        postgis: ['2.5', '3.0']
        variant: [default, alpine]
        platform: [arm64, amd64]
        exclude:
          - postgres: 13
            postgis: '2.5'
        include:
          - postgres: 12
            postgis: master
            variant: default
          - postgres: 13
            postgis: master
            variant: default
    name: Build ${{ matrix.platform }} docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: true
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}
      PUSH_IMAGES: ${{ (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to dockerhub
      uses: docker/login-action@v1
      if: ${{ env.PUSH_IMAGES }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set variant parameters
      id: variant-params
      run: |
        if [[ $VARIANT == default ]] ; then
            echo "::set-output name=context::./$VERSION"
            echo "::set-output name=version::$VERSION"
        else
            echo "::set-output name=context::./$VERSION/$VARIANT"
            echo "::set-output name=version::$VERSION-$VARIANT"
        fi

    - name: Build and push images
      uses: docker/build-push-action@v2
      with:
        context: ${{ steps.variant-params.outputs.context }}
        file: ${{ steps.variant-params.outputs.context }}/Dockerfile
        platforms: ${{ matrix.platform }}
        push: ${{ env.PUSH_IMAGES }}
        tags: derdaele/postgis:${{ steps.variant-params.outputs.version }}

