name: Docker PostGIS CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 * * 1'

defaults:
  run:
    shell: bash

jobs:
  make-docker-images:
    strategy:
      matrix:
        postgres: [9.5, 13]
        postgis: ['2.5', '3.0']
        variant: [default, alpine]
        exclude:
          - postgres: 13
            postgis: '2.5'
        include:
          - postgres: 12
            postgis: master
            variant: default
          - postgres: 13
            postgis: master
            variant: default
    name: Build docker image for ${{ matrix.postgres }}-${{ matrix.postgis }} variant ${{ matrix.variant }}
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.postgis == 'master' }}
    env:
      VERSION: ${{ matrix.postgres }}-${{ matrix.postgis }}
      VARIANT: ${{ matrix.variant }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to dockerhub
      uses: docker/login-action@v1
      if: ${{ (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Set variant parameters
      id: variant-params
      run: |
        if [[ $VARIANT == default ]] ; then
            echo "::set-output name=relative_path::"
            echo "::set-output name=version_suffix::"
        else
            echo "::set-output name=relative_path::$VARIANT"
            echo "::set-output name=version_suffix::-$VARIANT"
        fi
      env:
        VARIANT: ${{ matrix.variant }}

    - name: Build and push images
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.postgres }}-${{ matrix.postgis }}/${{ steps.variant-params.outputs.relative_path }}
        file: ./${{ matrix.postgres }}-${{ matrix.postgis }}/${{ steps.variant-params.outputs.relative_path }}/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ (github.ref == 'refs/heads/master') && (github.event_name != 'pull_request') }}
        tags: derdaele/postgis:${{ matrix.postgres }}-${{ matrix.postgis }}${{ steps.variant-params.outputs.version_suffix }}

